In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/refs/heads/master/winequality-red.csv")

In [ ]:
data['quality'].nunique()

6

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [ ]:
data['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [ ]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
data.describe().T

count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   5.636023   0.807569  3.00000   5.0000   

                           50%        75%        max  
fixed acidity          7.90000   9.200000   15.90000  
volatile acidity       0.52000   0.640000    1.58000  
citric acid            0.26000   0.420000    1.00000  
residual sugar         2.20000   2.600000   15.50000  
chlorides              0.07900   0.090000    0.61100  
free sulfur dioxide   14.00000  21.000000   72.00000  
total sulfur dioxide  38.00000  62.000000  289.00000  
density                0.99675   0.997835    1.00369  
pH                     3.31000   3.400000    4.01000  
sulphates              0.62000   0.730000    2.00000  
alcohol               10.20000  11.100000   14.90000  
quality                6.00000   6.000000    8.00000

In [ ]:
data.nunique()

fixed acidity            96
volatile acidity        143
citric acid              80
residual sugar           91
chlorides               153
free sulfur dioxide      60
total sulfur dioxide    144
density                 436
pH                       89
sulphates                96
alcohol                  65
quality                   6
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=data.drop("quality",axis=1)
y=data["quality"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [ ]:
from sklearn.preprocessing import StandardScaler
sls=StandardScaler()

In [ ]:
sls.fit(X_train,y_train)

StandardScaler()

SVR

In [ ]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train,y_train)

SVR()

In [ ]:
print(svr.intercept_)

[5.63701835]


In [ ]:
pred=svr.predict(X_test)

In [ ]:
X_test.shape
y_test.shape

(528,)

In [ ]:
pred.T

array([5.42880256, 5.07338685, 5.85662462, 5.74969382, 5.80249441,
       5.55162222, 5.07916273, 5.75497007, 5.62181806, 5.88729833,
       6.06290708, 5.74858359, 5.68970931, 5.67701247, 5.52504544,
       6.11561424, 5.16929084, 5.45621656, 5.9999959 , 5.28641983,
       5.85769982, 5.4968189 , 5.93178962, 6.03862039, 5.76183973,
       5.62514754, 5.89220469, 5.42657271, 5.17533813, 5.75868297,
       5.28863285, 5.37207911, 5.64842598, 5.80489907, 5.67209157,
       5.03378215, 5.91777553, 5.80119717, 5.76970731, 5.9797038 ,
       5.76706511, 5.03689426, 5.91587383, 5.04181647, 5.78513798,
       5.8080508 , 5.86219285, 5.69908081, 5.42083513, 5.81122594,
       4.95008088, 5.24559764, 5.89337784, 5.31523408, 4.97794914,
       4.86705595, 5.95393848, 5.27409346, 5.83402062, 5.6260082 ,
       5.48454064, 5.85812415, 5.50296775, 5.23340384, 6.24394859,
       5.57569272, 6.03134984, 5.38561815, 5.83819511, 5.31465518,
       5.98231328, 5.07035503, 5.64953559, 5.90908389, 6.04187

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
print(mean_squared_error(y_test,pred))
print(mean_absolute_error(y_test,pred))
print(np.sqrt(mean_squared_error(y_test,pred)))

0.16551881882989128
0.5526300616648337
0.5742528608212627
0.7433909211611571


In [ ]:
print(r2_score(y_test,pred))

0.16551881882989128


SVC

In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)

SVC()

In [ ]:
print(svc.n_support_)

[  8  34 383 409 129  11]


In [ ]:
print(svc.intercept_)

[-0.99340874 -1.00281662 -1.00210203 -0.99916512 -1.03467652 -0.99855121
 -0.99801527 -0.95369644  0.98775265  0.24210346  0.63178353  1.00590698
  0.72316148  1.0052014   0.99798127]


In [ ]:
X_train.shape

(1071, 11)

In [ ]:
X_test.shape

(528, 11)

In [ ]:
svc_pred=svc.predict(X_test)

In [ ]:
svc_pred

array([5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 7, 6,
       6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5,
       6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6,

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,svc_pred)

0.5